[package]
name = "variational-regression"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.15.0"
special = "0.8.1"
nalgebra = "0.29.0"